/**
 * Config-driven CRUD pages. Each entry renders through ResourcePage:
 *   key → API path, label, table columns, and form fields.
 * roles: which roles see the item in the sidebar.
 */
const MGMT = ['admin'];
const STAFF = ['admin', 'teacher', 'staff'];
const ALL = ['admin', 'teacher', 'staff', 'parent', 'learner'];

const RESOURCES = [
  { key: 'students', label: 'Students', roles: STAFF, columns: ['admission_number', 'first_name', 'last_name', 'class_id', 'parent_email', 'active'],
    fields: [
      { name: 'admission_number', label: 'Admission No.' },
      { name: 'first_name', label: 'First name', required: true },
      { name: 'last_name', label: 'Last name', required: true },
      { name: 'class_id', label: 'Class', type: 'ref', ref: 'classes', refLabel: 'name' },
      { name: 'parent_email', label: 'Parent email' },
      { name: 'date_of_birth', label: 'Date of birth', type: 'date' },
      { name: 'gender', label: 'Gender', type: 'select', options: ['Male', 'Female'] },
      { name: 'address', label: 'Address' },
      { name: 'emergency_contact', label: 'Emergency contact' },
      { name: 'emergency_phone', label: 'Emergency phone' },
    ] },
  { key: 'classes', label: 'Classes', roles: STAFF, columns: ['name', 'teacher_id', 'active'],
    fields: [
      { name: 'name', label: 'Class name', required: true },
      { name: 'teacher_id', label: 'Class teacher', type: 'ref', ref: 'users', refLabel: 'full_name' },
    ] },
  { key: 'learning-areas', label: 'Learning areas', roles: STAFF, columns: ['name', 'description', 'active'],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'description', label: 'Description', multiline: true },
    ] },
  { key: 'users', label: 'Users', roles: MGMT, columns: ['full_name', 'email', 'role', 'position', 'active'],
    fields: [
      { name: 'full_name', label: 'Full name', required: true },
      { name: 'email', label: 'Email', required: true },
      { name: 'role', label: 'Role', type: 'select', options: ['admin', 'teacher', 'parent', 'learner', 'staff'], required: true },
      { name: 'position', label: 'Position' },
      { name: 'password', label: 'Password (leave blank to keep)', type: 'password' },
    ] },
  { key: 'assignments', label: 'Assignments', roles: ALL, columns: ['title', 'class_id', 'learning_area_id', 'due_date', 'total_marks'],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', multiline: true },
      { name: 'class_id', label: 'Class', type: 'ref', ref: 'classes', refLabel: 'name' },
      { name: 'learning_area_id', label: 'Learning area', type: 'ref', ref: 'learning-areas', refLabel: 'name' },
      { name: 'due_date', label: 'Due date', type: 'date' },
      { name: 'total_marks', label: 'Total marks', type: 'number' },
      { name: 'academic_year', label: 'Academic year', type: 'number' },
      { name: 'term', label: 'Term', type: 'number' },
    ] },
  { key: 'assessments', label: 'Assessments', roles: STAFF, columns: ['title', 'assessment_type', 'class_id', 'assessment_date', 'total_marks'],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'assessment_type', label: 'Type', type: 'select', options: ['CAT', 'Exam', 'Project', 'Oral'] },
      { name: 'class_id', label: 'Class', type: 'ref', ref: 'classes', refLabel: 'name' },
      { name: 'learning_area_id', label: 'Learning area', type: 'ref', ref: 'learning-areas', refLabel: 'name' },
      { name: 'assessment_date', label: 'Date', type: 'date' },
      { name: 'total_marks', label: 'Total marks', type: 'number' },
      { name: 'term', label: 'Term', type: 'number' },
      { name: 'academic_year', label: 'Academic year', type: 'number' },
    ] },
  { key: 'announcements', label: 'Announcements', roles: ALL, columns: ['title', 'target_audience', 'priority', 'created_at'],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'content', label: 'Content', multiline: true, required: true },
      { name: 'target_audience', label: 'Audience', type: 'select', options: ['all', 'teachers', 'parents', 'learners'] },
      { name: 'priority', label: 'Priority', type: 'select', options: ['normal', 'high', 'urgent'] },
      { name: 'expires_at', label: 'Expires', type: 'date' },
    ] },
  { key: 'timetables', label: 'Timetables', roles: ALL, columns: ['class_id', 'day_of_week', 'start_time', 'end_time', 'learning_area_id', 'room'],
    fields: [
      { name: 'class_id', label: 'Class', type: 'ref', ref: 'classes', refLabel: 'name', required: true },
      { name: 'day_of_week', label: 'Day', type: 'select', options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], required: true },
      { name: 'start_time', label: 'Start (HH:MM)', required: true },
      { name: 'end_time', label: 'End (HH:MM)', required: true },
      { name: 'learning_area_id', label: 'Learning area', type: 'ref', ref: 'learning-areas', refLabel: 'name' },
      { name: 'teacher_id', label: 'Teacher', type: 'ref', ref: 'users', refLabel: 'full_name' },
      { name: 'room', label: 'Room' },
    ] },
  { key: 'resources', label: 'Learning resources', roles: ALL, columns: ['title', 'resource_type', 'url', 'created_at'],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', multiline: true },
      { name: 'resource_type', label: 'Type', type: 'select', options: ['Document', 'Video', 'Link', 'Book'] },
      { name: 'learning_area_id', label: 'Learning area', type: 'ref', ref: 'learning-areas', refLabel: 'name' },
      { name: 'url', label: 'URL' },
    ] },
  { key: 'schemes', label: 'Schemes of work', roles: STAFF, columns: ['title', 'class_id', 'term', 'week', 'topic'],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'class_id', label: 'Class', type: 'ref', ref: 'classes', refLabel: 'name' },
      { name: 'learning_area_id', label: 'Learning area', type: 'ref', ref: 'learning-areas', refLabel: 'name' },
      { name: 'academic_year', label: 'Year', type: 'number' },
      { name: 'term', label: 'Term', type: 'number' },
      { name: 'week', label: 'Week', type: 'number' },
      { name: 'topic', label: 'Topic' },
      { name: 'objectives', label: 'Objectives', multiline: true },
      { name: 'teaching_activities', label: 'Teaching activities', multiline: true },
      { name: 'assessment_methods', label: 'Assessment methods', multiline: true },
    ] },
  { key: 'lesson-plans', label: 'Lesson plans', roles: STAFF, columns: ['topic', 'class_id', 'lesson_date', 'term'],
    fields: [
      { name: 'topic', label: 'Topic', required: true },
      { name: 'class_id', label: 'Class', type: 'ref', ref: 'classes', refLabel: 'name' },
      { name: 'learning_area_id', label: 'Learning area', type: 'ref', ref: 'learning-areas', refLabel: 'name' },
      { name: 'lesson_date', label: 'Date', type: 'date' },
      { name: 'academic_year', label: 'Year', type: 'number' },
      { name: 'term', label: 'Term', type: 'number' },
      { name: 'objectives', label: 'Objectives', multiline: true },
      { name: 'teaching_methods', label: 'Methods', multiline: true },
      { name: 'materials', label: 'Materials', multiline: true },
      { name: 'activities', label: 'Activities', multiline: true },
      { name: 'assessment', label: 'Assessment', multiline: true },
      { name: 'homework', label: 'Homework', multiline: true },
    ] },
  { key: 'notes', label: 'Notes', roles: ALL, columns: ['topic', 'class_id', 'week', 'term'],
    fields: [
      { name: 'topic', label: 'Topic', required: true },
      { name: 'content', label: 'Content', multiline: true, required: true },
      { name: 'class_id', label: 'Class', type: 'ref', ref: 'classes', refLabel: 'name' },
      { name: 'learning_area_id', label: 'Learning area', type: 'ref', ref: 'learning-areas', refLabel: 'name' },
      { name: 'week', label: 'Week', type: 'number' },
      { name: 'term', label: 'Term', type: 'number' },
    ] },
  { key: 'academic-periods', label: 'Academic periods', roles: MGMT, columns: ['name', 'academic_year', 'term', 'is_current'],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'academic_year', label: 'Year', type: 'number', required: true },
      { name: 'term', label: 'Term', type: 'number', required: true },
      { name: 'start_date', label: 'Starts', type: 'date' },
      { name: 'end_date', label: 'Ends', type: 'date' },
      { name: 'is_current', label: 'Current period', type: 'select', options: ['true', 'false'] },
    ] },
  { key: 'grading-scales', label: 'Grading scale', roles: MGMT, columns: ['grade', 'min_percentage', 'max_percentage', 'remark', 'is_pass'],
    fields: [
      { name: 'grade', label: 'Grade', required: true },
      { name: 'min_percentage', label: 'Min %', type: 'number', required: true },
      { name: 'max_percentage', label: 'Max %', type: 'number', required: true },
      { name: 'remark', label: 'Remark' },
      { name: 'display_order', label: 'Order', type: 'number' },
    ] },
  { key: 'notifications', label: 'Notifications log', roles: MGMT, columns: ['recipient_email', 'subject', 'status', 'sent_at'],
    fields: [
      { name: 'recipient_email', label: 'Recipient email', required: true },
      { name: 'subject', label: 'Subject', required: true },
      { name: 'body', label: 'Body', multiline: true, required: true },
    ] },
];

export default RESOURCES;
